services:
  app:
    build: .
    env_file:
      - .env
    container_name: events_agregator

    depends_on:
      db:
        condition: service_healthy
    
    environment:
      DATABASE_URL: ${POSTGRES_CONNECTION_STRING}
      PYTHONPATH: /app
    
    ports:
      - "8000:8000"

    volumes:
      - .:/app

  outbox-worker:
    build: .
    command: python -m app.workers.ticket_outbox_process

  adminer:
    image: adminer
    container_name: events_aggregator_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    
  db:
    image: postgres:16-alpine
    container_name: events_agregator_db

    environment:
      
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - events_agregator_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE_NAME}"]
      interval: "3s"
      timeout: "3s"
      retries: 10

volumes:
  events_agregator_data: