"""outbox model

Revision ID: 3cf9455606dc
Revises: bd3f4b24d6be
Create Date: 2026-07-03 07:43:48.268694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cf9455606dc'
down_revision: Union[str, Sequence[str], None] = 'bd3f4b24d6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ticket.create_request', 'ticket.cancel_request', name='outboxeventtype', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', 'failed', name='outboxstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_status_created_at', 'outbox', ['status', 'created_at'], unique=False)
    op.add_column('tickets', sa.Column('external_ticket_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', name='ticketstatus', native_enum=False), nullable=False))
    op.add_column('tickets', sa.Column('seat', sa.String(length=16), nullable=False))
    op.add_column('tickets', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('tickets', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('uq_ticket_active_event_email', 'tickets', ['event_id', 'email'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.create_index('uq_ticket_active_event_seat', 'tickets', ['event_id', 'seat'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ticket_active_event_seat', table_name='tickets', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.drop_index('uq_ticket_active_event_email', table_name='tickets', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'email')
    op.drop_column('tickets', 'seat')
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'external_ticket_id')
    op.drop_index('ix_outbox_status_created_at', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
