"""use enum statuses

Revision ID: 4c048da32819
Revises: 4a1f3b5d8a4a
Create Date: 2026-06-29 13:27:01.925075

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c048da32819'
down_revision: Union[str, Sequence[str], None] = '4a1f3b5d8a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('new', 'published', name='eventstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('sync_runs', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('running', 'success', 'failed', name='syncstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_runs', 'status',
               existing_type=sa.Enum('running', 'success', 'failed', name='syncstatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=sa.Enum('new', 'published', name='eventstatus', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
