"""datetime updated check for outbox

Revision ID: 69011cdf2d22
Revises: 3cf9455606dc
Create Date: 2026-07-03 08:44:25.376254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69011cdf2d22'
down_revision: Union[str, Sequence[str], None] = '3cf9455606dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('outbox', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'processing', 'confirmed', 'canceled', 'failed', name='outboxstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox', 'status',
               existing_type=sa.Enum('pending', 'processing', 'confirmed', 'canceled', 'failed', name='outboxstatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('outbox', 'updated_at')
    # ### end Alembic commands ###
