"""varchar extend

Revision ID: bd3f4b24d6be
Revises: ed63d164b312
Create Date: 2026-06-29 14:21:47.169596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3f4b24d6be'
down_revision: Union[str, Sequence[str], None] = 'ed63d164b312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('new', 'published', 'finished', 'registration_closed', name='eventstatus', native_enum=False, length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.Enum('new', 'published', 'finished', 'registration_closed', name='eventstatus', native_enum=False, length=64),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    # ### end Alembic commands ###
