"""more enum varchar

Revision ID: db9ddc13cd57
Revises: 4c048da32819
Create Date: 2026-06-29 13:45:40.449152

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db9ddc13cd57'
down_revision: Union[str, Sequence[str], None] = '4c048da32819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('new', 'published', 'finished', 'registration_closed', name='eventstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.Enum('new', 'published', 'finished', 'registration_closed', name='eventstatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
